import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,Settings,Home as HomeIcon,Plus,Info,Play,ChevronLeft,ChevronRight,Heart,Download,Eye,Clock3,SlidersHorizontal,ArrowLeft,Share2,Check,UserRound,Film,MonitorPlay,Menu,X,ExternalLink,Volume2,Maximize,RotateCcw} from 'lucide-react';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'https://flixstar-api.onrender.com/api';
const IMG=(p,size='w500')=>p?`https://image.tmdb.org/t/p/${size}${p}`:'';
const BG=(p)=>p?`https://image.tmdb.org/t/p/original${p}`:'';
const year=x=>(x?.release_date||x?.first_air_date||'').slice(0,4);
const title=x=>x?.title||x?.name||'Untitled';
const mediaType=x=>x?.media_type||(x?.first_air_date?'tv':'movie');

function useRoute(){const [path,setPath]=useState(location.pathname+location.search);useEffect(()=>{const f=()=>setPath(location.pathname+location.search);addEventListener('popstate',f);return()=>removeEventListener('popstate',f)},[]);const nav=p=>{history.pushState({},'',p);setPath(p);window.scrollTo({top:0,behavior:'smooth'})};return {path,nav}}

function App(){
 const {path,nav}=useRoute(); const [query,setQuery]=useState(''); const [menu,setMenu]=useState(false);
 const goSearch=e=>{e.preventDefault();if(query.trim())nav(`/search?q=${encodeURIComponent(query.trim())}`)};
 const [lists,setLists]=useState(()=>JSON.parse(localStorage.getItem('flixstar-lists')||'[]'));
 const toggleList=item=>{setLists(prev=>{const exists=prev.some(x=>x.id===item.id&&mediaType(x)===mediaType(item));const n=exists?prev.filter(x=>!(x.id===item.id&&mediaType(x)===mediaType(item))):[...prev,item];localStorage.setItem('flixstar-lists',JSON.stringify(n));return n})};
 const isListed=item=>lists.some(x=>x.id===item.id&&mediaType(x)===mediaType(item));
 if(path.startsWith('/watch/')){const [, ,type,id]=path.split('/');return <Watch titleId={id} type={type} nav={nav}/>}
 if(path.startsWith('/person/'))return <Person id={path.split('/')[2]} nav={nav}/>;
 if(path.startsWith('/movie/'))return <Detail type="movie" id={path.split('/')[2]} nav={nav} listed={isListed} toggleList={toggleList}/>;
 if(path.startsWith('/tv/'))return <Detail type="tv" id={path.split('/')[2]} nav={nav} listed={isListed} toggleList={toggleList}/>;
 if(path.startsWith('/search'))return <SearchPage q={new URLSearchParams(location.search).get('q')||''} nav={nav}/>;
 if(path==='/movies')return <Listing type="movie" nav={nav} title="Movies" subtitle="Explore movies worth watching"/>;
 if(path==='/shows' || path==='/tv')return <Listing type="tv" nav={nav} title="TV Series" subtitle="Discover new TV series to watch"/>;
 if(path==='/my-list')return <MyList items={lists} nav={nav} toggle={toggleList}/>;
 if(path==='/settings')return <SettingsPage nav={nav}/>;
 return <><SiteNav nav={nav} query={query} setQuery={setQuery} onSearch={goSearch} menu={menu} setMenu={setMenu}/><Home nav={nav} listed={isListed} toggleList={toggleList}/><Footer nav={nav}/></>;
}

function SiteNav({nav,query,setQuery,onSearch,active,menu,setMenu}){return <header className="site-nav"><button className="brand" onClick={()=>nav('/')} aria-label="Flixstar"><span className="brand-mark">✦</span></button><div className="desktop-nav"><NavItem icon={<HomeIcon/>} text="Home" active={active==='home'} onClick={()=>nav('/')}/><NavItem text="Movies" active={active==='movies'} onClick={()=>nav('/movies')}/><NavItem text="Shows" active={active==='shows'} onClick={()=>nav('/shows')}/><NavItem text="My List" active={active==='list'} onClick={()=>nav('/my-list')}/><form className="nav-search" onSubmit={onSearch}><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder=""/><button aria-label="search" type="submit"/></form><button className="nav-icon" onClick={()=>nav('/settings')}><Settings size={19}/></button></div><button className="mobile-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button>{menu&&<div className="mobile-nav"><button onClick={()=>nav('/')}>Home</button><button onClick={()=>nav('/movies')}>Movies</button><button onClick={()=>nav('/shows')}>Shows</button><button onClick={()=>nav('/my-list')}>My List</button><button onClick={()=>nav('/settings')}>Settings</button></div>}</header>}
function NavItem({icon,text,active,onClick}){return <button className={`nav-pill ${active?'active':''}`} onClick={onClick}>{icon}{text}</button>}

function Home({nav,listed,toggleList}){const [d,setD]=useState(null);useEffect(()=>{fetch(`${API}/home`).then(r=>r.json()).then(setD).catch(()=>setD({}))},[]);const heroItems=d?.hero||d?.trending?.results||[];const [hero,setHero]=useState(0);useEffect(()=>{if(heroItems.length>1){const t=setInterval(()=>setHero(x=>(x+1)%heroItems.length),8000);return()=>clearInterval(t)}},[heroItems.length]);const h=heroItems[hero]||{};return <main className="home"><section className="home-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(4,12,12,.15) 0%,rgba(4,12,12,.05) 48%,rgba(4,12,12,.18) 100%),linear-gradient(0deg,rgba(3,12,12,.82),transparent 42%),url(${BG(h.backdrop_path)})`}}><SiteNav nav={nav} active="home" query="" setQuery={()=>{}} onSearch={()=>{}} menu={false} setMenu={()=>{}}/><div className="hero-inner"><div className="hero-title">{h.logo_path?<img src={IMG(h.logo_path,'w500')} alt={title(h)}/>:<h1>{title(h)}</h1>}</div><div className="hero-meta"><b>★ {h.vote_average?.toFixed(1)||'—'}/10</b><span>▣</span><span>{year(h)}</span><span>♡</span><span>{h.genres?.[0]?.name||'Movie'}</span></div><p>{h.overview||'Discover something new to watch.'}</p><div className="hero-actions"><button className="white-btn" onClick={()=>nav(`/${mediaType(h)}/${h.id}`)}><Play fill="currentColor" size={18}/> Play</button><button className="glass-group" onClick={()=>toggleList(h)}><Plus size={24}/><i></i><Info size={21}/></button></div></div><div className="dots">{heroItems.slice(0,8).map((_,i)=><button key={i} className={i===hero?'dot on':'dot'} onClick={()=>setHero(i)}/>)}</div></section><div className="home-body"><Shelf title="Continue Watching" items={d?.continueWatching?.results||[]} nav={nav} compact/><Shelf title="Trending Movies" items={d?.trendingMovies?.results||d?.popular?.results||[]} nav={nav}/><Shelf title="Rotten Tomatoes: Best Movies of All Time" items={d?.rtBest?.results||d?.topRated?.results||[]} nav={nav}/><Shelf title="Trending Series" items={d?.trendingSeries?.results||d?.tv?.results||[]} nav={nav}/><Shelf title="Movies on Netflix" items={d?.netflixMovies?.results||[]} nav={nav}/><Shelf title="TV Series on Netflix" items={d?.netflixShows?.results||[]} nav={nav}/><Shelf title="Mind-bending Movies" items={d?.mindBending?.results||d?.popular?.results||[]} nav={nav}/><Shelf title="Based on a True Story" items={d?.trueStory?.results||d?.topRated?.results||[]} nav={nav}/></div></main>}

function Shelf({title,items,nav,compact}){if(!items?.length)return null;return <section className={`shelf ${compact?'compact':''}`}><div className="shelf-head"><h2>{title}</h2><div><button onClick={()=>nav('/movies')}>View all <ChevronRight size={16}/></button></div></div><div className="poster-row">{items.slice(0,10).map((x,i)=><Poster key={`${mediaType(x)}-${x.id}-${i}`} item={x} nav={nav}/>)}</div></section>}
function Poster({item,nav,wide=false}){const type=mediaType(item);return <button className={`poster-card ${wide?'wide':''}`} onClick={()=>nav(`/${type}/${item.id}`)}><div className="poster-img">{item.poster_path?<img src={IMG(item.poster_path)} alt=""/>:<div className="poster-empty">FLIXSTAR</div>}{item.vote_average>0&&<span className="mini-rating">★ {item.vote_average.toFixed(1)}</span>}<span className="poster-hover"><Play fill="currentColor" size={24}/></span></div></button>}

function Listing({type,nav,title:heading,subtitle}){const [page,setPage]=useState(1);const [filter,setFilter]=useState({genre:'',sort:'popularity.desc',year:'',country:''});const [data,setData]=useState({results:[]});useEffect(()=>{const qs=new URLSearchParams({type,page,...filter});fetch(`${API}/discover?${qs}`).then(r=>r.json()).then(setData).catch(()=>{});},[type,page,filter]);return <><SiteNav nav={nav} active={type==='movie'?'movies':'shows'} query="" setQuery={()=>{}} onSearch={()=>{}} menu={false} setMenu={()=>{}}/><main className="listing-page"><PageTitle title={heading} subtitle={subtitle}/><div className="filter-bar"><button className="filter-chip"><SlidersHorizontal size={15}/> Filters</button><select value={filter.genre} onChange={e=>setFilter({...filter,genre:e.target.value})}><option value="">Genre</option><option value="28">Action</option><option value="35">Comedy</option><option value="18">Drama</option><option value="27">Horror</option><option value="878">Sci-Fi</option></select><select value={filter.year} onChange={e=>setFilter({...filter,year:e.target.value})}><option value="">Year</option>{Array.from({length:30},(_,i)=>2026-i).map(y=><option key={y}>{y}</option>)}</select><select value={filter.sort} onChange={e=>setFilter({...filter,sort:e.target.value})}><option value="popularity.desc">Popular</option><option value="vote_average.desc">Top Rated</option><option value="primary_release_date.desc">Newest</option></select><select value={filter.country} onChange={e=>setFilter({...filter,country:e.target.value})}><option value="">Country</option><option value="US">USA</option><option value="GB">UK</option><option value="KR">South Korea</option><option value="JP">Japan</option></select></div><div className="poster-grid">{data.results?.map((x,i)=><Poster item={x} nav={nav} key={`${x.id}-${i}`}/>)}</div><div className="pager"><button disabled={page<=1} onClick={()=>setPage(page-1)}><ChevronLeft/></button><span>{page}</span><button disabled={!data.total_pages||page>=Math.min(data.total_pages,20)} onClick={()=>setPage(page+1)}><ChevronRight/></button></div></main><Footer nav={nav}/></>}
function PageTitle({title,subtitle}){return <div className="page-title"><h1>{title}</h1><p>{subtitle}</p></div>}

function SearchPage({q,nav}){const [d,setD]=useState({results:[]});useEffect(()=>{if(q)fetch(`${API}/search?query=${encodeURIComponent(q)}`).then(r=>r.json()).then(setD)},[q]);return <><SiteNav nav={nav} query={q} setQuery={()=>{}} onSearch={()=>{}}/><main className="listing-page"><PageTitle title={`Search results`} subtitle={q?`Results for “${q}”`:''}/><div className="poster-grid">{d.results?.filter(x=>x.media_type!=='person').map((x,i)=><Poster item={x} nav={nav} key={`${x.id}-${i}`}/>)}</div></main></>}

function Detail({type,id,nav,listed,toggleList}){const [d,setD]=useState(null);const [tab,setTab]=useState('info');useEffect(()=>{fetch(`${API}/${type}/${id}`).then(r=>r.json()).then(setD)},[type,id]);if(!d)return <Loading/>;const t=title(d);return <><div className="detail-page" style={{backgroundImage:`linear-gradient(90deg,rgba(7,8,10,.9) 0%,rgba(7,8,10,.52) 45%,rgba(7,8,10,.88) 100%),linear-gradient(0deg,#070809 0%,transparent 45%),url(${BG(d.backdrop_path)})`}}><SiteNav nav={nav} active={type==='movie'?'movies':'shows'} query="" setQuery={()=>{}} onSearch={()=>{}}/><div className="detail-inner"><button className="back" onClick={()=>nav(type==='movie'?'/movies':'/shows')}><ArrowLeft size={19}/></button><div className="detail-copy"><div className="detail-label">{type==='tv'?'TV SERIES':'MOVIE'}</div><h1>{t}</h1><div className="detail-meta"><span>★ {d.vote_average?.toFixed(1)}/10</span><span>{year(d)}</span><span>{type==='tv'?`${d.number_of_seasons||0} Seasons`:(d.runtime?`${Math.floor(d.runtime/60)}h ${d.runtime%60}m`:'')}</span><span>{d.genres?.[0]?.name}</span></div><div className="detail-buttons"><button className="white-btn" onClick={()=>nav(`/watch/${type}/${id}`)}><Play fill="currentColor" size={18}/> Play</button><button className="circle-btn" onClick={()=>toggleList(d)}>{listed(d)?<Check/>:<Plus/>}</button><button className="circle-btn"><Share2/></button></div><p className="detail-overview">{d.overview}</p><div className="credits-line"><b>Director</b> {d.credits?.crew?.find(c=>['Director','Executive Producer'].includes(c.job))?.name||'—'}</div><div className="credits-line"><b>Cast</b> <button onClick={()=>document.getElementById('cast')?.scrollIntoView({behavior:'smooth'})}>{d.credits?.cast?.slice(0,4).map(c=>c.name).join(', ')||'—'}</button></div></div><aside className="facts"><div><span>Original Title</span><b>{d.original_title||d.original_name||t}</b></div><div><span>Release Date</span><b>{d.release_date||d.first_air_date||'—'}</b></div><div><span>Language</span><b>{d.original_language?.toUpperCase()||'—'}</b></div><div><span>Rating</span><b>{d.vote_average?.toFixed(1)||'—'}</b></div></aside></div></div>{type==='tv'&&<Episodes d={d} nav={nav}/>}<section className="below-detail" id="cast">{d.credits?.cast?.length>0&&<CastRow cast={d.credits.cast} nav={nav}/>}<Recommendation title="You Might Also Like" items={d.recommendations?.results?.length?d.recommendations.results:d.similar?.results||[]} nav={nav}/></section><Footer nav={nav}/></>}

function Episodes({d,nav}){const [season,setSeason]=useState(1);const [eps,setEps]=useState([]);useEffect(()=>{fetch(`${API}/tv/${d.id}/season/${season}`).then(r=>r.json()).then(x=>setEps(x.episodes||[])).catch(()=>{})},[d.id,season]);return <section className="episodes-wrap"><div className="episodes-head"><h2>Episodes</h2><div className="episode-controls"><button><SlidersHorizontal size={14}/> Ratings</button><button>↕ Oldest</button><button>◉ Mark watched</button><select value={season} onChange={e=>setSeason(e.target.value)}>{Array.from({length:d.number_of_seasons||1},(_,i)=><option value={i+1} key={i}>Season {i+1}</option>)}</select></div></div><div className="episode-grid">{eps.map(e=><button className="episode-card" key={e.id} onClick={()=>nav(`/watch/tv/${d.id}?season=${season}&episode=${e.episode_number}`)}><div className="episode-thumb">{e.still_path?<img src={IMG(e.still_path,'w500')}/>:<div/>}<span>{e.episode_number}</span><i><Play fill="currentColor" size={16}/></i><em>{e.runtime?`${e.runtime}m`:''}</em></div><h3>{e.name}</h3><p>{e.overview}</p></button>)}</div></section>}
function CastRow({cast,nav}){return <section className="cast-section"><div className="section-heading"><h2>Cast</h2></div><div className="cast-grid">{cast.slice(0,10).map(c=><button className="cast-card" key={c.id} onClick={()=>nav(`/person/${c.id}`)}><div>{c.profile_path?<img src={IMG(c.profile_path,'w185')}/>:<UserRound/>}</div><b>{c.name}</b><span>{c.character}</span></button>)}</div></section>}
function Recommendation({title,items,nav}){return items?.length?<section className="rec-section"><div className="section-heading"><h2>{title}</h2></div><div className="poster-row">{items.slice(0,8).map((x,i)=><Poster key={`${x.id}-${i}`} item={x} nav={nav}/>)}</div></section>:null}

function Person({id,nav}){const [d,setD]=useState(null);useEffect(()=>{fetch(`${API}/person/${id}`).then(r=>r.json()).then(setD)},[id]);if(!d)return <Loading/>;return <><SiteNav nav={nav}/><main className="person-page"><div className="person-head"><div className="person-photo">{d.profile_path?<img src={IMG(d.profile_path,'w500')}/>:<UserRound size={70}/>}</div><div><h1>{d.name}</h1><div className="person-meta"><span>Born {d.birthday||'—'}</span><span>{d.place_of_birth||'—'}</span></div><p>{d.biography||'Biography unavailable.'}</p><button className="read-more">Read More</button></div></div><section><div className="film-head"><h2>Filmography</h2><div><button className="switch active">Movies</button><button className="switch">TV Shows</button></div></div><div className="poster-row">{(d.combined_credits?.cast||[]).sort((a,b)=>year(b).localeCompare(year(a))).slice(0,12).map((x,i)=><Poster item={x} nav={nav} key={`${x.id}-${i}`}/>)}</div></section></main></>}

function MyList({items,nav,toggle}){return <><SiteNav nav={nav} active="list"/><main className="my-list-page"><PageTitle title="My Lists" subtitle="Save movies and shows you want to watch later"/><div className="list-tabs"><button className="active">My List</button><button>Watched</button></div>{items.length?<div className="poster-grid">{items.map((x,i)=><div className="list-item" key={`${x.id}-${i}`}><Poster item={x} nav={nav}/><button onClick={()=>toggle(x)} className="remove-list">×</button></div>)}</div>:<div className="empty-list"><Heart/><h3>No items yet</h3><p>Add movies and shows to your list using the + button.</p><button className="white-btn" onClick={()=>nav('/movies')}>Explore Movies</button></div>}</main></>}
function SettingsPage({nav}){return <><SiteNav nav={nav}/><main className="settings-page"><PageTitle title="Settings" subtitle="Manage your Flixstar preferences"/><div className="settings-card"><div className="setting"><div><b>Account</b><p>Guest account</p></div><button className="small-btn">Sign in</button></div><div className="setting"><div><b>Appearance</b><p>Dark mode</p></div><span className="toggle on"></span></div><div className="setting"><div><b>Autoplay</b><p>Play the next episode automatically</p></div><span className="toggle"></span></div><div className="setting"><div><b>Playback quality</b><p>Auto</p></div><button className="small-btn">Auto</button></div></div></main></>}
function Watch({titleId,type,nav}){const qs=new URLSearchParams(location.search);const season=qs.get('season');const episode=qs.get('episode');const [d,setD]=useState(null);useEffect(()=>{fetch(`${API}/${type}/${titleId}`).then(r=>r.json()).then(setD)},[titleId,type]);const t=d?title(d):'Loading';return <main className="watch-page"><div className="watch-top"><button onClick={()=>nav(`/${type}/${titleId}`)}><ArrowLeft/></button><span>{t}{season&&episode?` • S${season} E${episode}`:''}</span><button><ExternalLink size={18}/></button></div><div className="player"><iframe title={t} src="about:blank" allowFullScreen></iframe><div className="fake-controls"><button><RotateCcw/></button><button><Volume2/></button><span>0:00 / 0:00</span><div className="spacer"/><button><Download/></button><button><Maximize/></button></div></div><div className="watch-info"><h1>{t}</h1><p>Playback placeholder — connect your licensed video provider by replacing the iframe source.</p></div></main>}
function Loading(){return <div className="loading"><div className="spinner"/></div>}
function Footer({nav}){return <footer><button onClick={()=>nav('/')}>✦ FLIXSTAR</button><span>Discover • Watch • Save</span><div><button>Privacy</button><button>Terms</button></div></footer>}
createRoot(document.getElementById('root')).render(<App/>);
