import express from 'express';import cors from 'cors';import dotenv from 'dotenv';dotenv.config();
const app=express();app.use(cors());app.use(express.json());
const PORT=process.env.PORT||4000,KEY=process.env.TMDB_API_KEY;
async function tmdb(path,params={}){if(!KEY)throw new Error('TMDB_API_KEY is not configured');const u=new URL('https://api.themoviedb.org/3'+path);u.searchParams.set('api_key',KEY);u.searchParams.set('language','en-US');for(const[k,v]of Object.entries(params))if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,v);const r=await fetch(u);if(!r.ok)throw new Error(`TMDB ${r.status}`);return r.json()}
const safe=fn=>(req,res)=>fn(req,res).catch(e=>res.status(500).json({error:e.message}));
app.get('/api/home',safe(async(req,res)=>{const [trending,movies,tv,topRated,nowPlaying]=await Promise.all([tmdb('/trending/all/week'),tmdb('/movie/popular'),tmdb('/tv/popular'),tmdb('/movie/top_rated'),tmdb('/movie/now_playing')]);const withType=(x,type)=>({...x,results:x.results?.map(i=>({...i,media_type:i.media_type||type}))});res.json({hero:trending.results?.slice(0,8)||[],trending:withType(trending,'movie'),trendingMovies:withType(movies,'movie'),popular:withType(movies,'movie'),tv:withType(tv,'tv'),trendingSeries:withType(tv,'tv'),topRated:withType(topRated,'movie'),rtBest:withType(topRated,'movie'),latest:withType(nowPlaying,'movie'),continueWatching:{results:trending.results?.slice(3,9)||[]},netflixMovies:withType(movies,'movie'),netflixShows:withType(tv,'tv'),mindBending:withType(topRated,'movie'),trueStory:withType(topRated,'movie')})}));
app.get('/api/discover',safe(async(req,res)=>{const type=req.query.type==='tv'?'tv':'movie';const params={page:req.query.page||1,sort_by:req.query.sort||'popularity.desc',with_genres:req.query.genre||undefined};if(req.query.year)params[type==='movie'?'primary_release_year':'first_air_date_year']=req.query.year;if(req.query.country)params.with_origin_country=req.query.country;const data=await tmdb(`/discover/${type}`,params);res.json({...data,results:data.results.map(x=>({...x,media_type:type}))})}));
app.get('/api/search',safe(async(req,res)=>res.json(await tmdb('/search/multi',{query:req.query.query,page:req.query.page||1,include_adult:false}))));
app.get('/api/movie/:id',safe(async(req,res)=>res.json(await tmdb(`/movie/${req.params.id}`,{append_to_response:'credits,videos,images,recommendations,similar'}))));
app.get('/api/tv/:id',safe(async(req,res)=>res.json(await tmdb(`/tv/${req.params.id}`,{append_to_response:'credits,videos,images,recommendations,similar'}))));
app.get('/api/tv/:id/season/:season',safe(async(req,res)=>res.json(await tmdb(`/tv/${req.params.id}/season/${req.params.season}`))));
app.get('/api/person/:id',safe(async(req,res)=>res.json(await tmdb(`/person/${req.params.id}`,{append_to_response:'combined_credits,images'}))));
app.get('/api/health',(req,res)=>res.json({ok:true,name:'Flixstar'}));
app.listen(PORT,()=>console.log(`Flixstar API running on http://localhost:${PORT}`));
